### PR TITLE
Readme updates on the workflow now working

### PR DESCRIPTION
**Pull request by WillemVervoort**
### All Submissions:

* [X] Have you followed the guidelines in our **CONTRIBUTING** document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue. List the bug ID if applicable) #77 

README rendering now works

### New Feature Submissions checklist:

1. [X] Have you ensured there are no conflicts with major packages (e.g. tidyverse, MASS) or base R packages?
2. [ ] Does your new feature require documentation, and if so, have you updated the documentation?
3. [ ] Have you added tests for your features, and do your features pass all tests?
4. [ ] Have you linted your code with lintr locally prior to submission?
5. [ ] Have you styled your code with styler locally prior to submission?
6. [ ] Have you [benchmarked](https://www.alexejgossmann.com/benchmarking_r/) the performance of your code if applicable (e.g. with microbenchmark)?
7. [ ] Does your new feature comply with existing model APIs (e.g. for models, optimisation algorithms, objective functions)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you added tests for your core features and do your core features pass all tests?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Does your code run on all major platforms (Windows, macOS, Linux)?
* [ ] Have you demonstrated backwards compatibility and compatibility with the current development version, or discussed a potential break in backwards compatibility?
* [ ] Have you updated the package vignettes?

### CODE REVIEW

**Comment by WillemVervoort** [comment]
OK, fixing the fails, has to do with not pulling your standard_ci and R_linter to my fork

**Comment by WillemVervoort** [comment]
Well, I am stuck, updating standard_ci to my fork gives me more errors (I did a pull request from JosephGuillaume/master to my master and Readme branch). Probably need some help tomorrow on this. Not sure how I get this right. It seemed to work on my branch before...

**Comment by josephguillaume** [comment]
What errors do you get?

**Comment by WillemVervoort** [comment]
> What errors do you get?

Sorry, can I only see the check errors? Basically many of the checks seem to fail Rlinter,  and all the different hardware checks
R_styler and C_linter pass

**Comment by mortisflux** [comment]
> > What errors do you get?
> 
> Sorry, can I only see the check errors? Basically many of the checks seem to fail Rlinter, and all the different hardware checks

[This](https://github.com/WillemVervoort/hydromad/runs/822063456?check_suite_focus=true) seems to be the last time the render-readme action ran and it looks like it passed.

I think the reason it didn't run again has been mentioned previously (perhaps in another issue?) - the action is only set to run when README.Rmd itself is changed via a push:

```
on:
  push:
    paths:
      - README.Rmd
```

Opening a PR to josephguillaume/master or WillemVervoort/master won't run the readme-render. The [history of the actions](https://github.com/WillemVervoort/hydromad/actions) run in your repo shows that the only time readme-render runs is when the Readme.Rmd itself is updated e.g. here I can see you made a [small change](https://github.com/WillemVervoort/hydromad/commit/a712f623aa1d43a1251fe8ef72320465fb667431) to Readme.Rmd, and that triggered this action. If you did want it to run during a PR, you could try:

```
on:
  push:
    paths:
      - README.Rmd
  pull_request
```

**Comment by josephguillaume** [comment]
All the CI errors are normal, Willem - we have still many to fix, but they're not anything to do with this PR :-)
I'm merging this and we can improve on it later.
Closes #77

**Pull request merged**
