### PR TITLE
Code coverage action for workflow

### PR DESCRIPTION
**Pull request by mortisflux**
## Code coverage

This action will run `covr::codecov` on a push or pull to `master` to calculate the combined code coverage from tests and examples (this can be changed to just, tests for example, if required). To use this action, you will need to create an account on [https://codecov.io/](https://codecov.io/) and link it to this repository. The action will automatically upload the code coverage to codecov.io and will give you a report on how much and what sections of each function are covered. It will also allow you to create a badge for the repo!

I should add that the reason there are so many commits is because I created this branch from `roxygen2_documentation_v2` as the tests and examples all pass in that branch, which is a requirement for `covr` to work.

### All Submissions:

* [x] Have you followed the guidelines in our **CONTRIBUTING** document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by jnothman** [comment]
I think this is based off the wrong branch. 

I also think you can include coverage reporting in each existing test run, rather than adding a new one. I'm particular, code coverage should add together the code paths taken on different platforms, and report them all to an external service like those you mention above

**Comment by mortisflux** [comment]
> I think this is based off the wrong branch.

Is it? I see the changes I made to `roxygen2_documentation_v2` here e.g. "export xyplot.hydromad" and "added copyright to awbm.R".

> I also think you can include coverage reporting in each existing test run, rather than adding a new one. I'm particular, code coverage should add together the code paths taken on different platforms, and report them all to an external service like those you mention above

Do you mean running `covr` within R CMD check? `covr` is not recommended for running with R CMD check: [https://cran.r-project.org/web/packages/covr/readme/README.html](https://cran.r-project.org/web/packages/covr/readme/README.html)

I've based this off what I've seen in other R package repos that use GitHub actions e.g. [https://github.com/tidyverse/dplyr/blob/master/.github/workflows/test-coverage.yaml](https://github.com/tidyverse/dplyr/blob/master/.github/workflows/test-coverage.yaml). These only seem to run code coverage on one OS.

**Comment by jnothman** [comment]
I hadn’t expected this PR would include the changes from roxygen2_documentation_v2.

If this is what’s normal in R, then fine. 😊

**Comment by mortisflux** [comment]
> I hadn’t expected this PR would include the changes from roxygen2_documentation_v2. If this is what’s normal in R, then fine. 😊

No worries! The changes were included so that `covr` could run the tests and examples without them failing (otherwise `covr` exits).

**Comment by josephguillaume** [comment]
I'll have a look at creating an account on codecov.io, resolve the conflicts and then merge...

**Comment by josephguillaume** [comment]
Thanks!
Merged manually.

**Pull request closed without merging**
