### PR TITLE
version 0.9-27

### PR DESCRIPTION
**Pull request by josephguillaume**
Release 0.9-27

### CODE REVIEW

**Comment by josephguillaume** [comment]
@buzacott - could you please confirm this builds ok and add it to the hydromad.github.io repository?

New PRs will go to version 0.9-28.dev0 consistent with advice at https://github.com/josephguillaume/hydromad/issues/49

**Comment by buzacott** [comment]
> @buzacott - could you please confirm this builds ok and add it to the hydromad.github.io repository?
> 
> New PRs will go to version 0.9-28.dev0 consistent with advice at #49

No issues building binaries for this branch. I'll add them when you merge this into master and delete the 0.9-26-9000 binaries.

**Comment by josephguillaume** [comment]
Thanks! Just doing a fix to the tests to get some more green ticks... patrick had an API change.
Not sure what is wrong with test-coverage though.

**Comment by josephguillaume** [comment]
Didn't manage to fix ubuntu CI yet, but added issue #193 and merging

**Pull request merged**
