### PR TITLE
Deprecated testthat code fix

### PR DESCRIPTION
**Pull request by mortisflux**
## PR Description

This PR makes sure that the tests comply with the latest version of `testthat` and has modified the structure of `/tests`  accordingly. All tests, other than some that have been skipped (see below), pass when `devtools::test()` is run.

```
══ Results ══
Duration: 62.2 s

OK:       247
Failed:   0
Warnings: 20
Skipped:  3
```

The warnings include things such as:

```
test-calibration-results.R:34: warning: cwi+armax optim/SRIV gives reasonable result
did not converge after 12 iterations
```
```
test-calibration-results.R:50: warning: cmd+powuh SCE gives reasonable result
Maximum number of function evaluations or iterations reached.
```
```
test-with-exact-inputs.R:120: warning: SMA joint fitting methods work with exact inputs
Outliers detected outside burn-in period, returning to burn in
```

Tests have been skipped in `test-with-exact-outputs.R` as these are currently failing. I tried running them with the helper function `ts_equals`, but even running something such as `test <- ts_equals(Q_n1m0, Q_n1m0)` returns a function rather than some sort of numerical output, so any tests built on this fail. I've taken a stab at writing a similar function called `ts_helper2` (found in `helper-ts-equals.R`) that returns a ts output for use with `expect_equal()`. The test is currently throwing some errors:

```
* fitted(armax.ls.fit(cbind(U = U, Q = Q_n3s1), order = c(3, 1))) 
not equal to ts_equals2(Q_n3s1, fitted(armax.ls.fit(cbind(U = U, Q = Q_n3s1)))).
Mean relative difference: 0.003124182
```

which seem to be based on the tolerance supplied (e.g. 1e-5).

### All Submissions:

* [x] Have you followed the guidelines in our **CONTRIBUTING** document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue. List the bug ID if applicable)

### CODE REVIEW

**Comment by josephguillaume** [comment]
Thanks for the big effort!
Looks ok to me. Could you just remove `src/hydromad.so`  and it to .gitignore (sorry!), and then we're right to merge.

**Comment by josephguillaume** [comment]
Added issues #120 and #121 for the warnings and test-with-exact-outputs.R

**Comment by mortisflux** [comment]
> Could you just remove src/hydromad.so and it to .gitignore (sorry!), and then we're right to merge.

Done! Feel free to merge when you're ready.

**Comment by josephguillaume** [comment]
Thanks!

**Pull request merged**
