### PR TITLE
ET in bucket model exceeding available water

### LINKED ISSUE #188: bucket model, AET values confusing when S=0
## Issue summary:
ET (actual ET) values are larger than P[t] when S[t] = 0.

## Expected Behavior
When S_prev = 0 AND P[t] << E[t], ET[t] should be limited to S[t].

## Current Behavior
ET[t] is larger that P[t] when S_prev = 0, this doesn't make sense. See below.

## Possible Solution
Constraints: `(Etrans + Ebare)` cannot be > `S[t]`.
```r
# line 46 of https://github.com/josephguillaume/hydromad/blob/master/R/bucket.R
# 2021-05-03
# DEB: (ET_trans + ETbare) cannot exceed S[t]
 ET[t] <- Eintc + min(S[t], (Etrans + Ebare))
```

## Steps to Reproduce (for bugs)
```r
d <- structure(list(P = c(65, 59, 57, 28, 13, 3, 0, 1, 4, 20, 33, 
53), E = c(14, 22, 38, 54, 92, 125, 154, 140, 106, 66, 29, 14
)), class = "data.frame", row.names = c(NA, -12L))

m <- hydromad::hydromad(d, sma = "bucket", routing = NULL)
m <- update(m, Sb = 47, fc = 1, S_0 = 1, a.ss = 0.01, M = 0, etmult = 1, a.ei = 0)
res <- predict(m, return_state = TRUE)

# combine original PPT,PET with results
res <- data.frame(d, res)

# cleanup names
names(res) <- c('PPT', 'PET', 'U', 'S', 'ET')
```

```
| PPT| PET|      U|      S|     ET|
|---:|---:|------:|------:|------:|
|  65|  14| 51.000| 47.000| 14.000|
|  59|  22| 37.000| 47.000| 22.000|
|  57|  38| 19.000| 47.000| 38.000|
|  28|  54|  0.000| 21.000| 54.000|
|  13|  92|  0.000|  0.000| 66.553|
|   3| 125|  0.000|  0.000|  7.979|
|   0| 154|  0.000|  0.000|  0.000|
|   1| 140|  0.000|  0.000|  2.979|  <---
|   4| 106|  0.000|  0.000|  9.021|  <---
|  20|  66|  0.000|  0.000| 28.085|
|  33|  29|  0.000| 12.638| 20.362|
|  53|  14|  4.638| 47.000| 14.000|
```

## Context
Monthly water balance.

## Your Environment
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] hydromad_0.9-26     reshape_0.8.8       polynom_1.4-0       latticeExtra_0.6-29 lattice_0.20-41    
[6] zoo_1.8-9           soilDB_2.5.9        aqp_1.30            sharpshootR_1.8.1  
```

### PR DESCRIPTION
**Pull request by buzacott**
### All Submissions:

* [X] Have you followed the guidelines in our **CONTRIBUTING** document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

Closes #188 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue. List the bug ID if applicable)

As reported by @dylanbeaudette, ET was exceeding P when S was 0 or low. R and C code has been amended with the suggested fix and the issue appears to be resolved.

### CODE REVIEW

**Comment by dylanbeaudette** [comment]
Any progress? Thanks!

**Comment by josephguillaume** [comment]
Apologies for the delay...
It looks like the root cause of this problem was that S[t] was being updated with a max call, which would implicitly truncate the ET, i.e.
```R
        S[t] <- max(0, S_prev + P[t] - ET[t])
```
instead of 
```R
        S[t] <- S_prev + P[t] - ET[t]
```

I've removed two other calls like this that could theoretically affect U[t].
If we still get slightly negative S[t] for numerical reasons, the ideal solution would be to calculate ET[t] (or Use or Uss) in such a way that avoids it.

Could either of you please check whether the updated code still solves the issue, namely whether we do get negative S[t]?

I've also added a new issue (#190) for the test suite to check this kind of thing, in case of regression or if other models have similar issues.

**Comment by dylanbeaudette** [comment]
This is great! Thank you for the (better) fix. I'm not able to compile code on the target platform (work machine is locked-down Windows), but if this is implemented in R I can test. Any suggestions?

**Comment by buzacott** [comment]
Yep everything looks good, using the same test code as before

```r
> res
   PPT PET         U       S      ET
1   65  14 51.000000 47.0000 14.0000
2   59  22 37.000000 47.0000 22.0000
3   57  38 19.000000 47.0000 38.0000
4   28  54  0.000000 28.0000 47.0000
5   13  92  0.000000  0.0000 41.0000
6    3 125  0.000000  0.0000  3.0000
7    0 154  0.000000  0.0000  0.0000
8    1 140  0.000000  0.0000  1.0000
9    4 106  0.000000  0.0000  4.0000
10  20  66  0.000000  0.0000 20.0000
11  33  29  0.000000 12.6383 20.3617
12  53  14  4.638298 47.0000 14.0000
```

**Comment by josephguillaume** [comment]
Thank you both!

**Comment by dylanbeaudette** [comment]
Awesome! Any word on when the binary will be available?

**Comment by buzacott** [comment]
I've added a Windows binary `hydromad_0.9-26-9000.zip` of the main branch to the in development GitHub pages site for hydromad that you can test with:

https://github.com/hydromad/hydromad.github.io/blob/gh-pages/bin/windows/contrib/4.0/

**Comment by dylanbeaudette** [comment]
Great thanks, back to it and will test today. Has this binary percolated on up to links from the main Hydromad page?

**Comment by dylanbeaudette** [comment]
Tested and works well. Thank you for addressing the issue and posting the binary! Any idea on when this new version will be promoted to 'http://hydromad.catchment.org/bin/windows/contrib/' ?

Thanks!

**Comment by dylanbeaudette** [comment]
Quick check, any word on when hydromad_0.9-26-9000.zip will be in the "official" download repo? Thanks!

**Comment by buzacott** [comment]
Sorry for the delay Dylan, I'll contact Joseph and see if we can update hydromad repo

**Comment by buzacott** [comment]
@dylanbeaudette Apologies for the delay. I don't have access to the server to update the packages on the "official" repo, only @josephguillaume can do that but I'll see if we can organise to get that updated for you.

In the mean time,  I've added R 4.1 binaries for the head of the main branch and the release version that is on the official repo to the [hydromad.github.io](https://github.com/hydromad/hydromad.github.io) page while we try and sort this out

**Comment by josephguillaume** [comment]
Thanks for your patience @dylanbeaudette. @buzacott - that's exactly what we needed, thank you!
It is now possible to install hydromad using:
``` R
options(repos=c("https://hydromad.github.io",getOption("repos")))
install.packages("hydromad")
```

The github.io address will be a permanent home, but at least for the foreseeable future we also plan for the DNS entry http://hydromad.catchment.org to also point to https://hydromad.github.io

Long story, but we are haltingly moving to a new website and moving to the organisation https://github.com/hydromad so that I'm not on the critical path (you can see why).

@dylanbeaudette - if you could give any feedback on the new website https://hydromad.github.io , that would be great. In particular, is there anything you'd miss from the old one?
 
I was hoping we'd be able to release hydromad 1.0 before flicking the switch and turning off the old website, but clearly with my current workload it's not worth waiting.

**Comment by dylanbeaudette** [comment]
Thanks @josephguillaume and @buzacott. I see that version 0.27 has been released as a source-only package on GH? Do you expect to have a binary built soon? I can confirm that building on windows with R 4.1 works as expected. Are there plans to have version 1.0 on CRAN?

As for the website:

  * I liked the old one, but this new one follows a format that is increasingly becoming something of a standard among R packages
  * Any timeline on when this new website will become live?
  * Would you be interested in some tutorials / content that are based on NRCS soils data?

Thanks again for providing this package and the great documentation.

**Comment by buzacott** [comment]
The source and binaries have been added again to GitHub io page, they accidentally got deleted when I updated the website. You should be able to download them manually or install it using the instructs Joseph stated before

**Comment by dylanbeaudette** [comment]
Thanks. Are there plans to setup a preliminary package repository on the GitHub io site? This would make it possible to include the latest version of hydromad as a SUGGESTS when releasing to CRAN.

**Comment by josephguillaume** [comment]
> Are there plans to setup a preliminary package repository on the GitHub io site? 

I'm not sure what you mean by this. Nothing specific is needed to be able to use install_github and `options(repos=c("https://hydromad.github.io",getOption("repos")))` indeed already makes the package repository available

> Would you be interested in some tutorials / content that are based on NRCS soils data?

Very happy to discuss. What did you have in mind? What hydromad features or use cases would it demonstrate?

> Any timeline on when this new website will become live?

Whenever I'm comfortable turning off the old one. Your feedback was a little ambivalent, so I need to find time myself to confirm everything is ok.

**Comment by dylanbeaudette** [comment]
Thanks for the clarification. I didn't realize that I could use the new GH site as an "R package repository", so that I could specify it in the DESCRIPTION for the `sharpshootR` package. 
```
Additional_repositories: https://hydromad.github.io
```
That seems to work, and now I can push `sharpshootR` to CRAN.

[An example, based on real soil properties and a monthly water balance](http://ncss-tech.github.io/AQP/sharpshootR/monthly-WB.html). This uses a simple wrapper around `bucket.sim` to help users of soil survey data to perform monthly water balances. I would very much like any feedback that you might have. I'll save that for a new issue / email thread.

As for the website commentary: I do like the old website, but then again, I'm a fan of classic computers and ham radio. :) The new website is great and the more streamlined approach makes finding things very easy. I'll take another look and let you know if I see any obvious ommission.

**Pull request merged**
