### PR TITLE
Ci fixes

### PR DESCRIPTION
**Pull request by josephguillaume**
Ping @mortisflux @willemvervoort

I think this is what is needed for #77

### CODE REVIEW

**Comment by WillemVervoort** [comment]
I am not sure, does the push to github generate an error? If not and if the
Readme.md is regenerated (it does not seem to be regenerated atm), it
should be good to go.

**Comment by WillemVervoort** [comment]
Do you want me to test this on my branch?

**Comment by josephguillaume** [comment]
Not sure how to test, but I did notice that it says this only runs when README.rmd is pushed, which could be why it's not running in this case?

**Comment by WillemVervoort** [comment]
> 
> 
> Not sure how to test, but I did notice that it says this only runs when README.rmd is pushed, which could be why it's not running in this case?

OK, I can make a small change and push

**Comment by mortisflux** [comment]
> Not sure how to test, but I did notice that it says this only runs when README.rmd is pushed, which could be why it's not running in this case?

If set the action to run push and pull to master then you'll force the readme to compile.

> I think this is what is needed for #77

You may run into issues where hydromad may need extra dependencies (due to the suggested packages), as I think I mentioned in #77. From memory, dream, ppso and playwith (which is now removed) caused the problem. If you bump into that problem, you can implement the following code:

```
      - name: Install dependencies
        run: |
          remotes::install_github("TillF/ppso")
          remotes::install_url("http://download.r-forge.r-project.org/src/contrib/dream_0.4-2.tar.gz")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
```

**Comment by WillemVervoort** [comment]
See my comments on #77

**Comment by josephguillaume** [comment]
`remotes::install_deps(dependencies = TRUE)` tries to install suggested packages, so I've removed that.

I don't fully understand how the caching works, but it clearly wasn't working because `matrix.config` wasn't even defined.

**Comment by josephguillaume** [comment]
Addressed by #97

**Pull request closed without merging**
