### PR TITLE
Tutorial

### LINKED ISSUE #36: Vignette not building

### PR DESCRIPTION
**Pull request by WillemVervoort**
The is a new pull request to sort the tutorial. tutorial builds, but testthat fails on something that is not added by me
-- 1. Failure: formula works within functions (@test-statisti
(time.formula[3] - time.fun[3])/time.fun[3] is not strictly less than 0.1. Difference: 0.0163
### All Submissions:

* [X ] Have you followed the guidelines in our **CONTRIBUTING** document?
* [ X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

closes #36 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue. List the bug ID if applicable)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing core functionality to change) 

### New Feature Submissions checklist:

1. [x] Have you ensured there are no conflicts with major packages (e.g. tidyverse, MASS) or base R packages?
2. [x] Does your new feature require documentation, and if so, have you updated the documentation?
3. [ ] Have you added tests for your features, and do your features pass all tests?
4. [x ] Have you linted your code with lintr locally prior to submission?
5. [x] Have you styled your code with styler locally prior to submission?
6. [ ] Have you [benchmarked](https://www.alexejgossmann.com/benchmarking_r/) the performance of your code if applicable (e.g. with microbenchmark)?
7. [ ] Does your new feature comply with existing model APIs (e.g. for models, optimisation algorithms, objective functions)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you added tests for your core features and do your core features pass all tests?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Does your code run on all major platforms (Windows, macOS, Linux)?
* [ ] Have you demonstrated backwards compatibility and compatibility with the current development version, or discussed a potential break in backwards compatibility?
* [ x] Have you updated the package vignettes?

### CODE REVIEW

**Comment by buzacott** [comment]
> /document

I think the document workflow isn't working because the PR was created before it was merged into master.

But either way it is rather finicky and just manually adding the exports when making changes might just be easier.

**Comment by josephguillaume** [comment]
> > /document
> 
> I think the document workflow isn't working because the PR was created before it was merged into master.

Apparently it did work (I got an email) but it failed because this branch still has dependency on doRedis.

**Comment by josephguillaume** [comment]
I ran into a few more issues in merging this, but it looks like it's all good now. Thanks @buzacott  and @WillemVervoort !

**Pull request merged**
