### PR TITLE
pkgdown

### PR DESCRIPTION
**Pull request by buzacott**
### All Submissions:

* [X] Have you followed the guidelines in our **CONTRIBUTING** document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue. List the bug ID if applicable)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing core functionality to change) 

Converts the existing website generation to use `pkgdown`. The layout of the website mimics the existing website at hydromad.catchment.org. Website generation is currently in development mode in the `_pkgdown.yml`, the mode can be changed when it is ready to go live. Once the new website has been generated, any new changes can be tested by re-enabling development mode.

The website is built into the web/docs directory.

Including the current vignette should be a priority once that is building. We should also look into adding articles about specific hydromad features/models.

### New Feature Submissions checklist:

1. [x] Have you ensured there are no conflicts with major packages (e.g. tidyverse, MASS) or base R packages?
2. [ ] Does your new feature require documentation, and if so, have you updated the documentation?
3. [ ] Have you added tests for your features, and do your features pass all tests?
4. [ ] Have you linted your code with lintr locally prior to submission?
5. [ ] Have you styled your code with styler locally prior to submission?
6. [ ] Have you [benchmarked](https://www.alexejgossmann.com/benchmarking_r/) the performance of your code if applicable (e.g. with microbenchmark)?
7. [ ] Does your new feature comply with existing model APIs (e.g. for models, optimisation algorithms, objective functions)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you added tests for your core features and do your core features pass all tests?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Does your code run on all major platforms (Windows, macOS, Linux)?
* [ ] Have you demonstrated backwards compatibility and compatibility with the current development version, or discussed a potential break in backwards compatibility?
* [ ] Have you updated the package vignettes?

### CODE REVIEW

**Comment by buzacott** [comment]
Looks like I tried the PR before everything was linted/styled and before you could get the build checks to pass.

Maybe I need to rebase and try again?

**Comment by josephguillaume** [comment]
Sorry! Yes, it looks like it's just the styler that caused conflicts, so hopefully rebasing won't be difficult.
Note that linter and standard_ci are still failing, but let's aim to merge this before going further with those

**Comment by buzacott** [comment]
Forgot to comment again - looks like conflicts are gone now after rebasing.

**Comment by josephguillaume** [comment]
Thanks! This is a great base to use for the docs for the next release.

**Pull request merged**
