### PR TITLE
Fixing library calls and require calls

### LINKED ISSUE #61: Deal with 'library' or 'require' calls in package code
CRAN policy does not permit 'library' or 'require' calls in package code.

We load 'ff' 'ggplot2' 'parallel' 'playwith'

Instructions in R CMD CHECK say:
> Please use :: or requireNamespace() instead.
> See section 'Suggested packages' in the 'Writing R Extensions' manual.

Need to select a policy for dealing with suggested packages in hydromad.

### PR DESCRIPTION
**Pull request by WillemVervoort**
### All Submissions:

* [X] Have you followed the guidelines in our **CONTRIBUTING** document?
* [ X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

Closes #61 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue. List the bug ID if applicable)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing core functionality to change) 

### New Feature Submissions checklist:

1. [ ] Have you ensured there are no conflicts with major packages (e.g. tidyverse, MASS) or base R packages?
2. [ ] Does your new feature require documentation, and if so, have you updated the documentation?
3. [ ] Have you added tests for your features, and do your features pass all tests?
4. [ ] Have you linted your code with lintr locally prior to submission?
5. [X] Have you styled your code with styler locally prior to submission?
6. [ ] Have you [benchmarked](https://www.alexejgossmann.com/benchmarking_r/) the performance of your code if applicable (e.g. with microbenchmark)?
7. [ ] Does your new feature comply with existing model APIs (e.g. for models, optimisation algorithms, objective functions)?

### Changes to Core Features:

* [ X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you added tests for your core features and do your core features pass all tests?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Does your code run on all major platforms (Windows, macOS, Linux)?
* [ ] Have you demonstrated backwards compatibility and compatibility with the current development version, or discussed a potential break in backwards compatibility?
* [ ] Have you updated the package vignettes? 

This removes all calls to require() and replaces with requireNamespace() if needed. Only in the R subfolder, have not touched data, tests, or demo

### CODE REVIEW

**Comment by josephguillaume** [comment]
Hi Willem,

The conflicts listed here are probably because I ran styler on all these files earlier today.
Unless you have already done so, could you run styler::style_dir("R")?

**Comment by josephguillaume** [comment]
Actually it looks like you did run styler already? I'm not sure what's happening - it's hard to see your changes from the current master?

**Comment by WillemVervoort** [comment]
> Actually it looks like you did run styler already? I'm not sure what's happening - it's hard to see your changes from the current master?

Just ran styler, do you want me to run lintr as well? There is a bunch of stuff that is suggested by lintr, or are you fixing that elsewhere?

**Comment by WillemVervoort** [comment]
> Actually it looks like you did run styler already? I'm not sure what's happening - it's hard to see your changes from the current master?

I am not merging from master, I am merging from my "Require" branch, I will merge my master from yours to keep up to date

**Comment by WillemVervoort** [comment]
Looks like I should commit file by file or in groups of one or two? You want me to revert? I can ditch the branch and first update and then do it in smaller steps?

**Comment by josephguillaume** [comment]
Give me another minute to have a look. This is all a bit confusing, but no, don't worry about running lintr. The problem is that the two branches have somehow diverged too much for my brain to cope.

**Comment by josephguillaume** [comment]
I give up for tonight. @jnothman we might need your advice on how to deal with this

**Comment by jnothman** [comment]
It looks like there are things in master that have not been styled the same way as they have been in this branch. For example, in master:
https://github.com/josephguillaume/hydromad/blob/6d2ff34cc2532b0b74e4374ad801a901011595c5/R/ParetoFiltering.R#L37

In this branch:
https://github.com/josephguillaume/hydromad/blob/172be55ccbd66f08e015f8c48a0b65ab0e76cbf6/R/ParetoFiltering.R#L43-L53

So my suspicion is one of the following:
* There was something not quite right about the changes made by styler to master.
* There was different styler configuration (or version) in master as here.

Any ideas which?

**Comment by jnothman** [comment]
If both master and this branch validly used styler, but perhaps a different version, it begs the question: how do we ensure that users all apply styler with the same version and options? Perhaps by defining a script that can be used locally or by CI.

Running styler locally, I am also surprised at how slow it is, though at least contributors should ordinarily only apply it to modified files.

**Comment by josephguillaume** [comment]
I think styler is just not aggressive enough - I ran styler a few times and apparently styler is happy with both these versions.
@WillemVervoort - you did a fair bit of manual changes to style, right?
For did you apply the "Format code" option in RStudio, which seems to be different to what styler does?

I think I was put off/confused by two things:
- The changes in style (which is why I had thought that running style_dir might provide some clarity, but it didn't)
- There are changes listed here that are already in master, e.g. the readme yaml. I don't understand why it's showing them as additions.

**Comment by josephguillaume** [comment]
> how do we ensure that users all apply styler with the same version and options?

I don't think this is too much of an issue. The style is still acceptable. This is just a case where apparently Willem (inadvertently) didn't abide by the request to "Please don't restyle code that has nothing to do with your pull request." In addition to the changes to require/library, there were substantial edits to code style.

I'm happy to check over and accept the style if we can get a clean diff from current master, but this doesn't look like a clean diff from current master, and I'm not sure what is the best way to get there.

**Comment by jnothman** [comment]
> There are changes listed here that are already in master, e.g. the readme yaml. I don't understand why it's showing them as additions.

GitHub shows the diff between the pull request branch and its nearest common ancestor with the base branch. If the base branch ("master" here) gets updated with further commits, GitHub will automatically merge them, and their common ancestor will then be the latest base branch commit. If automatic merge is not possible, you will continue seeing comparisons to an old base until conflicts are resolved.

**Comment by WillemVervoort** [comment]
Is there a way to drop commits from this? Is because maybe last time I committed from a different branch? I thought I was being smart by starting from a new branch. Maybe I need to commit my branches to my master and then do a pull request from my master to your master.
The easiest way is probably to kill this PR, for me to delete the branch, then update everything on my master and start again. 

If we are all working on different parts, we will always have a problem that the branches diverge, I am not sure how we manage that

**Comment by jnothman** [comment]
> This is just a case where apparently Willem (inadvertently) didn't abide by the request to "Please don't restyle code that has nothing to do with your pull request." 

Ahh... right! Indeed, I like some of the new style.

So the challenge now is to split these changes into two pull requests: one focusing on the changes around require, and the other performing style improvements without changing require operation.

I can try guide you through this process. This is something that I've been meaning to write up a guide to for my colleagues at SIH too... So I might take my time and write it up as a case study!

**Comment by jnothman** [comment]
> Is there a way to drop commits from this?

Yes. The easiest way is probably to create a new branch from master, then cherry-pick individual commits from this branch onto that one. You may land up having to resolve merge conflicts, nonetheless. An equivalent alternative for cherry-picking in batch is called "interactive rebase" but its interface takes some time to get used to.

**Comment by WillemVervoort** [comment]
The manual changes I made would be more lintr than styler, so not sure.
I did reorganise a few long lines

**Comment by josephguillaume** [comment]
> If automatic merge is not possible, you will continue seeing comparisons to an old base until conflicts are resolved.

Ok. That makes sense, but ideally the contributor would resolve the conflicts :-P
Receiving contributions with difficult to read changes and conflicts is obviously a recurring problem, so I like your offer of treating this as a case study (regardless of its scope).

**Comment by jnothman** [comment]
> The manual changes I made would be more lintr than styler, so not sure. I did reorganise a few long lines.

I think of that as style. A future version of styler might do a better job of it. As opposed to "unused variable", "cyclomatic complexity", etc, which is code smell that is not style.

**Comment by WillemVervoort** [comment]
> > If automatic merge is not possible, you will continue seeing comparisons to an old base until conflicts are resolved.
> 
> Ok. That makes sense, but ideally the contributor would resolve the conflicts :-P
> Receiving contributions with difficult to read changes and conflicts is obviously a recurring problem, so I like your offer of treating this as a case study (regardless of its scope).

I am happy to go through all the conflicts and resolve them is that is the go
I just did not want to make major changes before you had a look

**Comment by josephguillaume** [comment]
> I am happy to go through all the conflicts and resolve them is that is the go

It's possible that you've somehow made your job here harder than it needs to be, so I'll defer to @jnothman on the best way to approach this.

**Comment by josephguillaume** [comment]
@WillemVervoort - if you want do work on something in the mean time, maybe have a go at the simhyd documentation :-)

**Comment by WillemVervoort** [comment]
> @WillemVervoort - if you want do work on something in the mean time, maybe have a go at the simhyd documentation :-)

Maybe, but I think I still need an up to date fork before I start doing that. I just pulled your fork master to my master, but it still says I am 10 commits ahead and this includes all the readme stuff. Maybe I need to make a pull request for my master to yours (which should be automatic as it is all the readme commits, which have already been incorporated from my readme branch). Just all very confusing with branch and fork. @jnothman please tell me where the knife is so I can spoon out these errors

**Comment by jnothman** [comment]
> Just all very confusing with branch and fork. @jnothman please tell me where the knife is so I can spoon out these errors

:D I think that might be a fork in the tree's branching, not a fork on the table.

> I just pulled your fork master to my master, but it still says I am 10 commits ahead and this includes all the readme stuff.

It shouldn't be hard to build your work on the latest hydromad master. For example:
```
git branch my-new-branch origin/master
git checkout my-new-branch
```
This builds on origin/master

**Comment by josephguillaume** [comment]
Willem, I was thinking the simhyd would be just one document, so could be dealt with without sorting this out. :-)

But maybe have a look at "Sync with upstream", here: https://github.com/michaeltlombardi/getting-github

The process should theoretically be:
```
git remote add upstream https://github.com/josephguillaume/hydromad.git

# Run commands one at a time, checking for errors
git fetch upstream
git rebase upstream/master
git push -u origin master
git checkout -b new branch
```

If you do this every time you start a new branch, you'll be up-to-date at the start. Before you go for the PR, you can then check your up to date again with:
```
git fetch upstream
git rebase upstream/master
```

**Comment by WillemVervoort** [comment]
I understand the making a branch link to origin, but I thought my origin for my branches was always my master on my fork. 

I think the mistake I made is to not commit back to the fork and then do a pull request to the master on Joseph's fork. Instead I did a PR from my branch of my fork to the master on Joseph's fork. Technically this is possible, but now my master is behind on Joseph's merged master. However if I then update my master from his master it gets confusing. I think you are saying it will not incorporate the merge from my branch because it does not know about this? Seems to me the easiest fix is for me to change it manually, and then work out some way of making sure my master is up to date and kill my branches

**Comment by jnothman** [comment]
> origin for my branches was always my master on my fork.

Right. So then you need to add another remote, not called origin, like `git remote add upstream https://github.com/josephguillaume/hydromad`... now you can do `git fetch upstream`

**Comment by josephguillaume** [comment]
If you want a clean start for master, maybe do:
```
git remote add upstream https://github.com/josephguillaume/hydromad.git
git fetch upstream
git branch temp upstream/master
git checkout temp
git push --force --set-upstream origin origin/master
git checkout master
git pull
git branch --delete temp
```
Note that the push --force will completely reset your master.

You can then start from scratch again:
```
git branch my-new-branch origin/master
git checkout my-new-branch
```

**Comment by josephguillaume** [comment]
Just to clarify, I'm not suggesting you restart your edits to library, require etc from scratch! The suggested clean start was if you want to work on other things in the mean time.

**Comment by WillemVervoort** [comment]
I will try that, but I will have to first stash my changes somewhere so it
easier to get back

**Comment by josephguillaume** [comment]
Or just start a new local repo in a different folder

**Comment by WillemVervoort** [comment]
I have tried the rebase using
https://github.com/michaeltlombardi/getting-github  , but every time I try
that my master becomes more commits ahead of your master. So I am doing
something totally wrong.
Github is suggesting I run a pull request, maybe that is the way to go

**Comment by jnothman** [comment]
Hmm... I should probably have been working on other projects, but I decided to develop this guide, which is more based on your questions than a case study in them:
https://gist.github.com/jnothman/8c33ebdd20e5f3ebd788126703ee6cf8

Please provide feedback!

**Comment by buzacott** [comment]
> I have tried the rebase using https://github.com/michaeltlombardi/getting-github , but every time I try that my master becomes more commits ahead of your master. So I am doing something totally wrong. Github is suggesting I run a pull request, maybe that is the way to go
> […](#)

Are your commits to the master branch? If so then rebasing will add your commits on top so you will be ahead.

**Comment by WillemVervoort** [comment]
I don't have more time today, maybe tomorrow afternoon Alex can have a zoom
session with me and maybe hold my hand. I am really out of my depth here

Willem

**Comment by jnothman** [comment]
I do not find rebasing on an updated branch head to often be a helpful procedure. Merging in the updated branch is usually a simpler way to achieve the same goal (albeit with a messier commit history that could be squashed when merged).

More useful here would be to take this diff and use `git add --patch` to select bits that you want in the "require" patch, commit that, then take the changes you have left to create a new branch. Maybe I can write this up too. "Back to the case study: Splitting one branch into two Pull Requests"

**Comment by jnothman** [comment]
## Splitting one branch into multiple patches

Back to the case study: In a complicated situation like this, we may have a
long history of commits composing the current messy diff.  One approach to
resolving this is to create several separate branches (and corresponding pull
requests) with more focussed diffs.

Let's assume we're currently working on `my-branch`.

1. Create a copy of the current branch where we will commit the first patch
   `git checkout -b patch1`.
2. Find a common place to start, the nearest common ancestor with origin's
   master: `base=$(git merge-base my-branch origin/master)`.
3. Reset `patch1` back to `$base`, keeping all changes, but not adding them.
   `git reset $base`.
4. Add parts of files that you want `git add --patch`.
5. Add any whole files that are missing from the patch with `git status` then
   `git add path/to/file`.
6. Commit `git commit -m "blah blah blah"`, then push this branch if
   appropriate.
7. If you look at `git diff`, the remainder should be changes you want in
   another patch commit. Let's open a new branch like `patch2` at `$base`
   keeping those changes in our working copy: `git checkout -b patch2 $base`.
8. Repeat from step 4. until all the changes have been committed (and pushed,
   and pull requests opened) in a focussed pull request.

**Comment by mortisflux** [comment]
@jnothman thanks for writing up this tidbit, it is super useful! I think I'll be facing some of the issues that have been mentioned here soon, as my initial documentation conversion trial was done on an older version of master obtained prior to styling (i.e. files in /R will need to be updating accordingly).

> I do not find rebasing on an updated branch head to often be a helpful procedure. Merging in the updated branch is usually a simpler way to achieve the same goal (albeit with a messier commit history that could be squashed when merged).

Are there any instances where would you recommend using rebase (other than the example of picking particular commits), if any?

**Comment by jnothman** [comment]
> Are there any instances where would you recommend using rebase (other than the example of picking particular commits), if any?

I used to use rebase a lot, before GitHub added the "squash and merge" button, to clean up commit histories. I rarely use it these days without `--interactive`. Since `git rebase --interactive` can do everything that `git rebase` can do, plain old rebase is mostly relegated to git tool developers.

**Pull request closed without merging**
